import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { GetStaticProps } from 'next';
import Layout, { siteTitle } from '@/components/layout';
import DateUtil from '@/components/date';
import { getSortedPostsData } from '@/lib/posts';
import utilStyles from '@/styles/utils.module.css';
import { PostType } from '@/types/post';

export default function Home({ allPostsData }: {
  allPostsData?: PostType[]
}) {
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData && allPostsData.map(postData => (
            <li className={utilStyles.listItem} key={postData.id}>
              <Link href={`/posts/${postData.id}`}>{postData.title}</Link>
              <br />
              <small className={utilStyles.lightText}>
                <DateUtil dateString={postData?.date} />
              </small>
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = () => {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData
    }
  };
}